(function(root,definition) { if (typeof exports === 'object') { module.exports = definition(); } else if (typeof define === 'function' && define.amd) { define([], definition); } else { root["Views"] = definition(); } })(this,function() { return (function(){var Views = {};Views["chapter.xhtml"] = function anonymous(it) {
var out='<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Chapter '+(it.index)+'</title><link rel="stylesheet" href="style.css" type="text/css" /></head><body><div id="chapter">';if(it.title){out+='<h3 class="title">'+(it.title)+'</h3>';}else{out+='<h3 class="title">Chapter '+(it.index)+'</h3>';}out+=(it.text)+'</div></body></html>';return out;
};
Views["container.xml"] = function anonymous(it) {
var out='<?xml version="1.0" encoding="UTF-8"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>';return out;
};
Views["content.opf"] = function anonymous(it) {
var out='<?xml version="1.0" encoding="UTF-8"?><package xmlns="http://www.idpf.org/2007/opf" unique-identifier="BookID" version="2.0" ><metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf"><dc:title>'+(it.title)+'</dc:title> <dc:creator opf:role="aut">'+(it.author)+'</dc:creator><dc:language>'+(it.lang)+'</dc:language> <dc:rights>Public Domain</dc:rights> <dc:publisher>EPubBuilder.js</dc:publisher> <dc:identifier id="BookID" opf:scheme="UUID">'+(it.uuid)+'</dc:identifier></metadata><manifest><item id="style" href="style.css" media-type="text/css" /><item id="titlepage" href="title_page.xhtml" media-type="application/xhtml+xml" />';var arr1=it.chapters;if(arr1){var index,i1=-1,l1=arr1.length-1;while(i1<l1){index=arr1[i1+=1];out+='<item id="chapter'+(index)+'" href="chap'+(index)+'.xhtml" media-type="application/xhtml+xml" />';} } out+='</manifest><spine toc="ncx"><itemref idref="titlepage"/>';var arr2=it.chapters;if(arr2){var index,i2=-1,l2=arr2.length-1;while(i2<l2){index=arr2[i2+=1];out+='<itemref idref="chapter'+(index)+'"/>';} } out+='</spine></package>';return out;
};
Views["style.css"] = function anonymous(it) {
var out='#book .title, #book .author {text-align:center;font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;}#chapter {margin: 2em;}#chapter .title {text-align: center;}';return out;
};
Views["title_page.xhtml"] = function anonymous(it) {
var out='<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Title Page</title><link rel="stylesheet" href="style.css" type="text/css" /></head><body><div id="book"><p>&nbsp;</p><h2 class="title">'+(it.title)+'</h2><p>&nbsp;</p><h3 class="author">'+(it.author)+'</h3></div></body></html>';return out;
};
Views["toc.ncx"] = function anonymous(it) {
var out='<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE ncx PUBLIC "-//NISO//DTD ncx 2005-1//EN" "http://www.daisy.org/z3986/2005/ncx-2005-1.dtd"><ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1"> <head> <meta name="dtb:uid" content="015ffaec-9340-42f8-b163-a0c5ab7d0611"/> <meta name="dtb:depth" content="2"/> <meta name="dtb:totalPageCount" content="0"/> <meta name="dtb:maxPageNumber" content="0"/> </head> <docTitle> <text>Sample .epub eBook</text> </docTitle> <navMap> <navPoint id="navPoint-1" playOrder="1"> <navLabel> <text>Sample Book</text> </navLabel> <content src="Text/title_page.xhtml"/> </navPoint> <navPoint id="navPoint-2" playOrder="2"> <navLabel> <text>A Sample .epub Book</text> </navLabel> <content src="Text/title_page.xhtml#heading_id_3"/> <navPoint id="navPoint-3" playOrder="3"> <navLabel> <text>Title Page</text> </navLabel> <content src="Text/title_page.xhtml#heading_id_4"/> </navPoint> <navPoint id="navPoint-4" playOrder="4"> <navLabel> <text>Chapter 1</text> </navLabel> <content src="Text/chap01.xhtml"/> </navPoint> <navPoint id="navPoint-5" playOrder="5"> <navLabel> <text>Chapter 2</text> </navLabel> <content src="Text/chap02.xhtml"/> </navPoint> </navPoint> </navMap></ncx>';return out;
}; return Views;})(); });